# generated by datamodel-codegen:
#   filename:  set_price.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetPriceParameter(BaseModel):
    pass

    class Config:
        extra = Extra.allow
