# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class TargetPriceOracleV3Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    administrator: str
    last_epoch: str
    price: str
    response_threshold: str
    valid_epoch: str
    valid_respondants: List[str]
    valid_response: str
    valid_script: str
    valid_sources: List[str]
    validity_window_in_epochs: str
