# generated by datamodel-codegen:
#   filename:  burn.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BurnParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    token_id: str
    token_amount: str
