# generated by datamodel-codegen:
#   filename:  xtzToToken.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class XtzToTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to: str
    minTokensBought: str
    deadline: str
