# generated by datamodel-codegen:
#   filename:  cashToToken.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CashToTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to: str
    minTokensBought: str
    cashSold: str
    deadline: str
