# generated by datamodel-codegen:
#   filename:  removeLiquidity.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveLiquidityParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to: str
    lqtBurned: str
    minCashWithdrawn: str
    minTokensWithdrawn: str
    deadline: str
