# generated by datamodel-codegen:
#   filename:  tokenToCash.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TokenToCashParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to: str
    tokensSold: str
    minCashBought: str
    deadline: str
