# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Intents(BaseModel):
    class Config:
        extra = Extra.forbid

    token_amount: str
    start_timestamp: str


class YouvesFa2IntentsV3Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    collateral_token_address: str
    collateral_token_id: str
    engine_address: str
    intents: Dict[str, Intents]
    target_price_oracle: str
    token_address: str
    token_id: str
