# generated by datamodel-codegen:
#   filename:  internal_withdraw.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class InternalWithdrawParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
