# generated by datamodel-codegen:
#   filename:  internal_deposit.json

from __future__ import annotations

from pydantic import BaseModel


class InternalDepositParameter(BaseModel):
    __root__: str
