# generated by datamodel-codegen:
#   filename:  internal_bailout.json

from __future__ import annotations

from pydantic import BaseModel


class InternalBailoutParameter(BaseModel):
    __root__: str
