# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TzbtcAmmStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    lqtAddress: str
    lqtTotal: str
    tokenAddress: str
    tokenPool: str
    xtzPool: str
