# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class GenericTargetPriceOracleV1Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    administrator: str
    last_epoch: str
    prices: Dict[str, str]
    response_threshold: str
    valid_btc_price: str
    valid_defi_price: str
    valid_epoch: str
    valid_respondants: List[str]
    valid_script: str
    valid_sources: List[str]
    valid_xtz_price: str
    validity_window_in_epochs: str
