# generated by datamodel-codegen:
#   filename:  internal_withdraw.json

from __future__ import annotations

from pydantic import BaseModel


class InternalWithdrawParameter(BaseModel):
    __root__: str
