# generated by datamodel-codegen:
#   filename:  set_vault_balance.json

from __future__ import annotations

from pydantic import BaseModel


class SetVaultBalanceParameter(BaseModel):
    __root__: str
