# generated by datamodel-codegen:
#   filename:  create_vault.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CreateVaultParameter(BaseModel):
    __root__: Optional[str]
