# generated by datamodel-codegen:
#   filename:  liquidate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class LiquidateParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vault_owner: str
    token_amount: str
