# generated by datamodel-codegen:
#   filename:  internal_liquidate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class InternalLiquidateParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vault_owner: str
    token_amount: str
