# generated by datamodel-codegen:
#   filename:  internal_fulfill_intent.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class InternalFulfillIntentParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    collateral_token_amount: str
