# generated by datamodel-codegen:
#   filename:  remove_intent.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveIntentParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
