# generated by datamodel-codegen:
#   filename:  internal_fulfill_intent.json

from __future__ import annotations

from pydantic import BaseModel


class InternalFulfillIntentParameter(BaseModel):
    __root__: str
