# generated by datamodel-codegen:
#   filename:  advertise_intent.json

from __future__ import annotations

from pydantic import BaseModel


class AdvertiseIntentParameter(BaseModel):
    __root__: str
