# generated by datamodel-codegen:
#   filename:  execute_intent.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ExecuteIntentParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    token_amount: str
