# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    token_id: str


class Administrator(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Dict[str, Any]


class VaultContexts(BaseModel):
    class Config:
        extra = Extra.forbid

    allows_settlement: bool
    balance: str
    is_being_liquidated: bool
    minted: str


class YouvesFa2EngineStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    accrual_update_timestamp: str
    administrators: List[Administrator]
    collateral_token_contract: str
    collateral_token_id: str
    compound_interest_rate: str
    governance_token_contract: str
    options_contract: str
    reference_interest_rate: str
    reward_pool_contract: str
    savings_pool_contract: str
    sender: str
    target_price: str
    target_price_oracle: str
    token_contract: str
    token_id: str
    total_supply: str
    vault_contexts: Dict[str, VaultContexts]
