# generated by datamodel-codegen:
#   filename:  internal_settle_with_vault.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class InternalSettleWithVaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vault_owner: str
    token_amount: str
    recipient: str
