# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetPriceOracleV1Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    last_epoch: str
    price: str
    signature_threshold: str
    time_window: str
    trusted_certificates: Dict[str, Dict[str, Any]]
    trusted_keys: Dict[str, Dict[str, Any]]
    validity_window_in_epochs: str
