# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    token_id: str


class Administrator(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Dict[str, Any]


class YouvesSavingsStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    administrators: List[Administrator]
    current_balance: str
    disc_factor: str
    dist_factor: str
    dist_factors: Dict[str, str]
    engine_address: str
    last_balance: str
    sender: str
    stakes: Dict[str, str]
    token_address: str
    token_id: str
    total_stake: str
    vesting_contract: str
    vesting_duration_in_seconds: str
